### ISSUE TITLE
Suporte a 10.98

### ISSUE THREAD

**Issue by hygorrasec** [ottools/ObjectBuilder#12]
Olá!

Eu consigo adaptar uma versão anterior para o cliente 10.98.
Porém, essa nova nem com reza braba eu consigo. Por qual motivo ele está bloqueado (ou eu não estou fazendo correto) para utilizar recursos da versão 10.98 ?

Obrigado!

**Comment by Mignari** [comment]
Oi
A versão desse repositório nunca funcionou para 10.98, mas existe uma versão nos fóruns adaptada pra 10.98 por outro programador. Eu não sei se ele disponibilizou as sources.

**Comment by Diego-OT** [comment]
@Mignari  sumiu vei, cade vc? Att o builder com as novas flags pra nós <3
