### ISSUE TITLE
Merge no 0.3.3

### ISSUE THREAD

**Issue by hygorrasec** [ottools/ObjectBuilder#13]
Fala irmão.

Você consegue adaptar o Merge na versão 0.3.3?
Ele só existe na 0.4.5, porém não funciona pra versão 10.98

Se puder pelo menos ensinar a adaptar essa função na versão 0.3.3 seriamos muito grato.
Obrigado!

https://image.prntscr.com/image/52HEuoprR1aPWBMKbM0Fzw.jpeg

**Comment by Mignari** [comment]
Infelizmente não. Mas o código completo está aqui no repositório, espero que outra pessoa faça.
