### ISSUE TITLE
[BUG]Can't edit animation Duration

### ISSUE THREAD

**Issue by AngelOfDeaths** [ottools/ObjectBuilder#26]
Hello, I can't edit now animation duration.

**Comment by Mignari** [comment]
Is Improved Animations enabled?
This feature is enabled by default in client versions 10.50+
For previous versions, you need to enable it, but you would also need to enable it in the client

**Comment by AngelOfDeaths** [comment]
@Mignari okay, can you add arrows to +1/-1 animation? when you have 50+ animation in one item it's painful when you try move it to +1
