### ISSUE TITLE
Update OB to client 10.98

### ISSUE THREAD

**Issue by luanluciano93** [ottools/ObjectBuilder#3]
Tudo bom? Gostaria de saber se vai atualizar para a versão 10.98?

**Comment by Mignari** [comment]
E ai 🤙
No momento, o projeto está apenas em manutenção e correções de bugs. Não pretendo adicionar suporte para novas versões.

**Comment by luanluciano93** [comment]
Que pena, a maioria dos derivados estão "ultrapassados", e isso ajudaria muito a levanta-los.

Ótimo trabalho cara!

**Comment by Anderson0xFF** [comment]
como compilar isso ?
