### ISSUE TITLE
Blank Sprite Reset Option

### ISSUE THREAD

**Issue by elewental** [ottools/ObjectBuilder#37]
Sometimes If I create a sprite that have a square fully transparent and drag there accidentally a wrong sprite, I need to remove it, then I have two options: 
1 - create a 100% blank sprite to move there
2 - delete the whole object configuration and start again

That's why Im suggesting the creation of this button:
![image](https://user-images.githubusercontent.com/52132367/155803446-0dafb4d3-39ad-4853-83d5-4cc349ba3112.png)

Or:
![image](https://user-images.githubusercontent.com/52132367/155803550-d0216b2a-c2cc-454f-8b00-9ae3d488904f.png)

**Comment by Mignari** [comment]
This is a really necessary feature
Was added in version v0.4.9


![Screenshot_184](https://user-images.githubusercontent.com/6242139/155826489-a4c9aa26-135c-4312-8413-200eb968833f.png)
