### ISSUE TITLE
Possibility to port it to 10.76

### ISSUE THREAD

**Issue by JoseEduardo** [ottools/ObjectBuilder#52]
I wonder if there will be the possibility to be done with that is compatible with version 10.76, if not in the plans, could you give the coordinates to be made these changes?

At worst would inform me if there is changing the version of my SPR and DAT for version 10.76?

Thank you and congratulations for the work

**Comment by DarkShinz** [comment]
At "\src\firstRun\version, add the line: 
<version value="1076" string="10.76" dat="37DF" spr="54F03CE9" otb="0"/>

Now, rebuild all the again.

**Comment by DarkShinz** [comment]
If you do so, could you share the release? xD I can't compile it myself.

**Comment by Athenuz** [comment]
I've uploaded my fix on the bountysource website and the thread at OtLand (:

**Comment by ronpetit** [comment]
This is the link in otland for the Athenuz fix

https://otland.net/threads/bounty-added-to-grant-object-builder-10-76-support.233227/page-3#post-2290690

**Comment by Athenuz** [comment]
https://www.bountysource.com/issues/11478897-possibility-to-port-it-to-10-76

Actually here's the fix now, on the "View Source" Button you can see the download link.

Install and enjoy!

**Comment by ronpetit** [comment]
This solve the issue right?, it says "possibility to port to 10.76" and Athenuz made a way to use it, is not a definitive port but it work on OTC @DarkShinz @Mignari

**Comment by DarkShinz** [comment]
We've discussed it at the forums. As it is a quick fix and not a full porting, we'll not consider it as the fix we want, but we will wait him to fully port it. You can read for yourself at the forums! :)

**Comment by beastn** [comment]
Jano has updated this

See thread
https://otland.net/threads/bounty-added-to-grant-object-builder-10-76-support.233227/page-7#post-2328098

Please close this issue.
