### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by sirakx** [ottools/ObjectBuilder#56]
I have an error. believe a new certificate to compile the program. but when I try to open the file AIR gives me error. tells me that the certificate is not the same as the program you help me?

**Comment by Mignari** [comment]
Each developer have its own certificate. You need to remove the installed version with my certificate in order to install a new one.

**Comment by sirakx** [comment]
apology discomfort friend, how I can do that? I'm just using adobe builder

**Comment by Mignari** [comment]
If you have the Object Builder installed, just uninstall it.
