### ISSUE TITLE
More Mounts

### ISSUE THREAD

**Issue by blackz13** [ottools/ObjectBuilder#57]
how can i add more than 10 mounts? i can't find it on the sources

**Comment by Mignari** [comment]
Perhaps you are confusing it with the list of mounts in the server.
"mount" in the Object Builder is an outfit state.

Mount = 0
![outfit001](https://cloud.githubusercontent.com/assets/6242139/13744640/e3c7b2d6-e9c7-11e5-8c4d-957eeabb096e.png)

Mount = 1
![outfit002](https://cloud.githubusercontent.com/assets/6242139/13744641/e3d22ff4-e9c7-11e5-8713-779293334a45.png)

If you want to add more mounts to the server, just add the mount as outfit.
![mount-list](https://cloud.githubusercontent.com/assets/6242139/13744795/fb2f5eb4-e9c8-11e5-997c-39da717c2356.png)

Now add the mount in the server: **data/XML/mounts.xml**
The attribute **clientid** is the id of the outfit (previous image).
https://github.com/otland/forgottenserver/blob/master/data/XML/mounts.xml

-----

Ok, if you really want to add more states, you can change it here:

https://github.com/ottools/ObjectBuilder/blob/master/src/otlib/components/ThingTypeEditor.mxml#L1127

add a new line _maximum="20"_

**Comment by blackz13** [comment]
And about addons, is the same way? I am saying on the patterny / z, the slider go to 10, i want more, this is the state u are talking?
