### ISSUE TITLE
Outfit colors blend options

### ISSUE THREAD

**Issue by armadaazteca** [ottools/ObjectBuilder#63]
Hello, I tried to use some of the latest versions of this tool and I can't find where should I go to update the color layers of the outfits, It used to be a section on left side of the properties, I don't remember the label, but it was something like blending options or layers and using that one, I could see the layers for the custom colors of the outfits with this option. Could you please explain to me where is this feature now? or is it missing?

**Comment by Mignari** [comment]
Thanks for reporting the issue.
